"""
Analytics Data Models

Pydantic models for Domain Analytics architecture.
Used by Domain Analytics subagents and Analytics Magister.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DomainMetrics(BaseModel):
    """Raw domain metrics collected from data sources

    This is the raw data collected by Domain Analytics subagents
    before aggregation and processing.
    """
    domain: str = Field(..., description="Domain name (seo, content, ads, ai)")
    period: Dict[str, str] = Field(..., description="Time period (start, end)")
    raw_data: Dict[str, Any] = Field(..., description="Raw metrics data")
    collected_at: datetime = Field(default_factory=datetime.now, description="Collection timestamp")
    source: Optional[str] = Field(None, description="Data source (e.g., 'google_analytics', 'yandex_metrika')")

    class Config:
        json_schema_extra = {
            "example": {
                "domain": "seo",
                "period": {"start": "2026-05-01", "end": "2026-05-05"},
                "raw_data": {
                    "organic_sessions": 1500,
                    "avg_position": 12.5,
                    "backlinks": 234
                },
                "collected_at": "2026-05-05T10:00:00Z",
                "source": "google_search_console"
            }
        }


class AggregatedMetrics(BaseModel):
    """Aggregated domain metrics

    This is the processed data sent from Domain Analytics subagents
    to Analytics Magister for strategic analysis.
    """
    domain: str = Field(..., description="Domain name (seo, content, ads, ai)")
    period: Dict[str, str] = Field(..., description="Time period (start, end)")
    summary: Dict[str, Any] = Field(..., description="High-level summary metrics")
    kpis: Dict[str, float] = Field(..., description="Key Performance Indicators")
    trends: Dict[str, str] = Field(..., description="Trend analysis (growing/stable/declining)")
    insights: List[str] = Field(default_factory=list, description="Domain-specific insights")
    aggregated_at: datetime = Field(default_factory=datetime.now, description="Aggregation timestamp")
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Data confidence score")

    class Config:
        json_schema_extra = {
            "example": {
                "domain": "seo",
                "period": {"start": "2026-05-01", "end": "2026-05-05"},
                "summary": {
                    "organic_traffic": 15000,
                    "avg_position": 12.5,
                    "backlinks_growth": 23
                },
                "kpis": {
                    "organic_sessions": 15000.0,
                    "keyword_visibility": 0.75,
                    "domain_authority": 45.0
                },
                "trends": {
                    "traffic_trend": "growing",
                    "rankings_trend": "stable",
                    "backlinks_trend": "growing"
                },
                "insights": [
                    "Organic traffic вырос на 15% за месяц",
                    "TOP-10 позиций увеличилось на 8 ключевых слов"
                ],
                "aggregated_at": "2026-05-05T10:15:00Z",
                "confidence": 0.92
            }
        }


class Correlation(BaseModel):
    """Cross-domain correlation

    Represents a correlation between metrics from different domains.
    """
    domain_a: str = Field(..., description="First domain")
    metric_a: str = Field(..., description="Metric from first domain")
    domain_b: str = Field(..., description="Second domain")
    metric_b: str = Field(..., description="Metric from second domain")
    correlation_coefficient: float = Field(..., ge=-1.0, le=1.0, description="Pearson correlation coefficient")
    strength: str = Field(..., description="Correlation strength (weak/moderate/strong)")
    direction: str = Field(..., description="Correlation direction (positive/negative)")
    insight: str = Field(..., description="Human-readable insight")

    class Config:
        json_schema_extra = {
            "example": {
                "domain_a": "seo",
                "metric_a": "organic_traffic",
                "domain_b": "ads",
                "metric_b": "cpa",
                "correlation_coefficient": -0.78,
                "strength": "strong",
                "direction": "negative",
                "insight": "SEO traffic ↑ → Ads CPA ↓ (органика снижает стоимость привлечения)"
            }
        }


class StrategicInsight(BaseModel):
    """Strategic insight from cross-domain analysis

    High-level actionable insight generated by Analytics Magister.
    """
    title: str = Field(..., description="Insight title")
    description: str = Field(..., description="Detailed description")
    affected_domains: List[str] = Field(..., description="Domains affected by this insight")
    priority: str = Field(..., description="Priority level (critical/high/medium/low)")
    impact: str = Field(..., description="Expected impact")
    recommendation: str = Field(..., description="Actionable recommendation")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score")
    generated_at: datetime = Field(default_factory=datetime.now, description="Generation timestamp")

    class Config:
        json_schema_extra = {
            "example": {
                "title": "SEO investment reduces paid acquisition costs",
                "description": "Strong negative correlation between organic traffic and CPA",
                "affected_domains": ["seo", "ads"],
                "priority": "high",
                "impact": "Увеличение SEO бюджета на 20% снизит Ads CPA на 15%",
                "recommendation": "Перераспределить 20% бюджета из Ads в SEO",
                "confidence": 0.85,
                "generated_at": "2026-05-05T10:30:00Z"
            }
        }


class CrossDomainMetrics(BaseModel):
    """Cross-domain aggregated metrics

    Combined metrics from all domains with correlations and strategic insights.
    Used by Analytics Magister for executive reporting.
    """
    period: Dict[str, str] = Field(..., description="Time period (start, end)")
    domain_metrics: Dict[str, AggregatedMetrics] = Field(..., description="Metrics by domain")
    correlations: List[Correlation] = Field(default_factory=list, description="Cross-domain correlations")
    strategic_insights: List[StrategicInsight] = Field(default_factory=list, description="Strategic insights")
    overall_summary: Dict[str, Any] = Field(..., description="Overall summary across all domains")
    aggregated_at: datetime = Field(default_factory=datetime.now, description="Aggregation timestamp")

    class Config:
        json_schema_extra = {
            "example": {
                "period": {"start": "2026-05-01", "end": "2026-05-05"},
                "domain_metrics": {
                    "seo": {"domain": "seo", "summary": {}, "kpis": {}, "trends": {}, "insights": []},
                    "content": {"domain": "content", "summary": {}, "kpis": {}, "trends": {}, "insights": []},
                    "ads": {"domain": "ads", "summary": {}, "kpis": {}, "trends": {}, "insights": []},
                    "ai": {"domain": "ai", "summary": {}, "kpis": {}, "trends": {}, "insights": []}
                },
                "correlations": [],
                "strategic_insights": [],
                "overall_summary": {
                    "total_traffic": 50000,
                    "total_conversions": 1250,
                    "overall_roi": 4.2
                },
                "aggregated_at": "2026-05-05T10:45:00Z"
            }
        }


class AnalyticsAlert(BaseModel):
    """Analytics alert for critical changes

    Sent by Analytics Magister when critical metrics change.
    """
    severity: str = Field(..., description="Alert severity (critical/high/medium/low)")
    title: str = Field(..., description="Alert title")
    message: str = Field(..., description="Alert message")
    affected_domains: List[str] = Field(..., description="Affected domains")
    metric: str = Field(..., description="Metric that triggered alert")
    current_value: float = Field(..., description="Current metric value")
    threshold_value: float = Field(..., description="Threshold value")
    change_percent: float = Field(..., description="Percentage change")
    recommendation: Optional[str] = Field(None, description="Recommended action")
    created_at: datetime = Field(default_factory=datetime.now, description="Alert timestamp")

    class Config:
        json_schema_extra = {
            "example": {
                "severity": "high",
                "title": "SEO traffic dropped significantly",
                "message": "Organic traffic dropped 25% in last 24 hours",
                "affected_domains": ["seo", "content"],
                "metric": "organic_sessions",
                "current_value": 11250.0,
                "threshold_value": 15000.0,
                "change_percent": -25.0,
                "recommendation": "Investigate Google algorithm update or technical issues",
                "created_at": "2026-05-05T14:30:00Z"
            }
        }
