"""Add payments table

Revision ID: 07c3a0904edc
Revises: c8de5ad75fa5
Create Date: 2026-05-16 21:36:00.780652+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '07c3a0904edc'
down_revision: Union[str, None] = 'c8de5ad75fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_email_hash'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_specialty'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_email_events_email_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_occurred_at'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_email_templates_tier'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_workflows_lead_id'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_status'), table_name='email_workflows')
    op.drop_table('email_workflows')
    op.drop_index(op.f('ix_scheduled_emails_scheduled_at'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_status'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_workflow_id'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_emails',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('workflow_id', sa.NUMERIC(), nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=False),
    sa.Column('html_content', sa.TEXT(), nullable=False),
    sa.Column('text_content', sa.TEXT(), nullable=False),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('sendgrid_message_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['email_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_emails_workflow_id'), 'scheduled_emails', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_status'), 'scheduled_emails', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_scheduled_at'), 'scheduled_emails', ['scheduled_at'], unique=False)
    op.create_table('email_workflows',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('lead_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tier', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('current_step', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_workflows_status'), 'email_workflows', ['status'], unique=False)
    op.create_index(op.f('ix_email_workflows_lead_id'), 'email_workflows', ['lead_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tier', sa.VARCHAR(length=10), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=False),
    sa.Column('subject_template', sa.TEXT(), nullable=False),
    sa.Column('html_template', sa.TEXT(), nullable=False),
    sa.Column('text_template', sa.TEXT(), nullable=False),
    sa.Column('ai_prompt', sa.TEXT(), nullable=True),
    sa.Column('variables', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_tier'), 'email_templates', ['tier'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('email_id', sa.NUMERIC(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('event_data', sqlite.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['scheduled_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_occurred_at'), 'email_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_email_id'), 'email_events', ['email_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('name_encrypted', sa.TEXT(), nullable=False),
    sa.Column('phone_encrypted', sa.TEXT(), nullable=False),
    sa.Column('email_encrypted', sa.TEXT(), nullable=False),
    sa.Column('email_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('clinic_name_encrypted', sa.TEXT(), nullable=False),
    sa.Column('message_encrypted', sa.TEXT(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fz152_consent', sa.BOOLEAN(), nullable=False),
    sa.Column('fz152_consent_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('fz152_consent_ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('utm_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utm_medium', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utm_campaign', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utm_content', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utm_term', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=False),
    sa.Column('linear_task_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('tier', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_specialty'), 'leads', ['specialty'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_email_hash'), 'leads', ['email_hash'], unique=False)
    # ### end Alembic commands ###
