# AIM/src/aim/teacher/audit_report.py
"""Audit report generator."""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from aim.teacher.gap_detector import Gap, GapSeverity


@dataclass
class AuditResult:
    """Result of subagent audit."""
    subagent_name: str
    github_repos: list[str]
    gaps: list[Gap]
    score: float  # 0-100, higher is better


class AuditReportGenerator:
    """Generate audit reports in markdown format."""

    def generate(self, result: AuditResult) -> str:
        """
        Generate audit report.

        Args:
            result: Audit result

        Returns:
            Markdown report
        """
        report = f"""# Audit Report: {result.subagent_name}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Score:** {result.score:.1f}/100
**Status:** {"✅ PASS" if result.score >= 80 else "⚠️ NEEDS IMPROVEMENT" if result.score >= 60 else "❌ FAIL"}

---

## GitHub Repositories Analyzed

"""

        if result.github_repos:
            for repo in result.github_repos:
                report += f"- {repo}\n"
        else:
            report += "- No repositories found\n"

        report += "\n---\n\n## Gaps Detected\n\n"

        if not result.gaps:
            report += "✅ No gaps detected! Subagent follows all best practices.\n"
        else:
            # Group by severity
            by_severity = {}
            for gap in result.gaps:
                severity = gap.severity.value
                if severity not in by_severity:
                    by_severity[severity] = []
                by_severity[severity].append(gap)

            # Critical
            if "critical" in by_severity:
                report += "### 🔴 CRITICAL (implement immediately)\n\n"
                for gap in by_severity["critical"]:
                    report += f"**{gap.pattern}**\n"
                    report += f"- {gap.description}\n"
                    report += f"- **Action:** {gap.recommendation}\n\n"

            # High
            if "high" in by_severity:
                report += "### 🟡 HIGH (plan for next sprint)\n\n"
                for gap in by_severity["high"]:
                    report += f"**{gap.pattern}**\n"
                    report += f"- {gap.description}\n"
                    report += f"- **Action:** {gap.recommendation}\n\n"

            # Medium
            if "medium" in by_severity:
                report += "### 🟢 MEDIUM (backlog)\n\n"
                for gap in by_severity["medium"]:
                    report += f"**{gap.pattern}**\n"
                    report += f"- {gap.description}\n"
                    report += f"- **Action:** {gap.recommendation}\n\n"

        report += "---\n\n"
        report += "**Generated by Teacher Agent**\n"

        return report

    def save(self, result: AuditResult, output_path: Path) -> None:
        """
        Save report to file.

        Args:
            result: Audit result
            output_path: Output file path
        """
        report = self.generate(result)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report)
